### ISSUE TITLE
Broken xref

### ISSUE THREAD

**Issue by zakariamehbi** [scribeocr/scribe.js#30] opened 2024-12-12 19:07 UTC
Hello,

We're experiencing the following error related to a specific PDF file. Unfortunately, we can't provide the file.

```
format error: cannot recognize version marker
format error: cannot recognize version marker
format error: cannot recognize version marker
{ name: 'Error', message: 'no objects found' }
warning: trying to repair broken xref
warning: repairing PDF document
warning: name is too long
```

**Comment by Balearica** [comment] 2024-12-22 03:56
Closing for now, will reopen if somebody can provide an example file.  Unfortunately, due to how complex the PDF file format is, this type of thing is inherently impossible to figure out without a reproducible example.

**Closed by Balearica** 2024-12-22 03:56 UTC
